# Generated by Django 5.2.6 on 2025-09-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_remove_conversation_uniq_post_buyer_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='post',
        ),
    ]
